export const orders = [
  {
    id: 2,
    status: "belum diproses",
    total: 0,
    createdAt: "2024-12-31T01:37:53.104Z",
    updatedAt: "2024-12-31T01:37:53.104Z",
    produk: [
      {
        id: 3,
        productId: 1,
        pesananId: 2,
        quantity: 2,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 4,
        productId: 2,
        pesananId: 2,
        quantity: 1,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
      {
        id: 3,
        productId: 1,
        pesananId: 2,
        quantity: 2,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 4,
        productId: 2,
        pesananId: 2,
        quantity: 1,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
      {
        id: 3,
        productId: 1,
        pesananId: 2,
        quantity: 2,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 4,
        productId: 2,
        pesananId: 2,
        quantity: 1,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
      {
        id: 3,
        productId: 1,
        pesananId: 2,
        quantity: 2,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 4,
        productId: 2,
        pesananId: 2,
        quantity: 1,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
    ],
  },
  {
    id: 3,
    status: "belum diproses",
    total: 0,
    createdAt: "2024-12-31T01:38:23.996Z",
    updatedAt: "2024-12-31T01:38:23.996Z",
    produk: [
      {
        id: 5,
        productId: 1,
        pesananId: 3,
        quantity: 2,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 6,
        productId: 2,
        pesananId: 3,
        quantity: 1,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
    ],
  },
  {
    id: 5,
    status: "belum diproses",
    total: 33000,
    createdAt: "2024-12-31T01:42:17.100Z",
    updatedAt: "2024-12-31T01:42:17.116Z",
    produk: [
      {
        id: 9,
        productId: 1,
        pesananId: 5,
        quantity: 2,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 10,
        productId: 2,
        pesananId: 5,
        quantity: 1,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
    ],
  },
  {
    id: 6,
    status: "belum diproses",
    total: 165000,
    createdAt: "2024-12-31T01:42:49.997Z",
    updatedAt: "2024-12-31T01:42:50.006Z",
    produk: [
      {
        id: 11,
        productId: 1,
        pesananId: 6,
        quantity: 5,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 12,
        productId: 2,
        pesananId: 6,
        quantity: 10,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
    ],
  },
  {
    id: 7,
    status: "belum diproses",
    total: 165000,
    createdAt: "2024-12-31T01:43:53.074Z",
    updatedAt: "2024-12-31T01:43:53.085Z",
    produk: [
      {
        id: 13,
        productId: 1,
        pesananId: 7,
        quantity: 5,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 14,
        productId: 2,
        pesananId: 7,
        quantity: 10,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
    ],
  },
  {
    id: 8,
    status: "belum diproses",
    total: 165000,
    createdAt: "2024-12-31T01:45:33.716Z",
    updatedAt: "2024-12-31T01:45:33.728Z",
    produk: [
      {
        id: 15,
        productId: 1,
        pesananId: 8,
        quantity: 5,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 16,
        productId: 2,
        pesananId: 8,
        quantity: 10,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
    ],
  },
  {
    id: 9,
    status: "belum diproses",
    total: 165000,
    createdAt: "2024-12-31T01:45:41.486Z",
    updatedAt: "2024-12-31T01:45:41.495Z",
    produk: [
      {
        id: 17,
        productId: 1,
        pesananId: 9,
        quantity: 5,
        product: {
          id: 1,
          name: "Product 3",
          price: 11000,
        },
      },
      {
        id: 18,
        productId: 2,
        pesananId: 9,
        quantity: 10,
        product: {
          id: 2,
          name: "Product 2",
          price: 11000,
        },
      },
    ],
  },
];
